
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/game?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Rome
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:        
        hbm2ddl.auto: update     
        format_sql: true
        show_sql: true
  mail:
 
 
  servlet:
    multipart:
      location: ${java.io.tmpdir}


